### ISSUE TITLE
Escape HTML characters in Notes

### ISSUE THREAD

**Issue by andythigpen** [andythigpen/Review#88]
I discovered this issue when trying to enter < in the Notes text box and the subsequent output was not displayed.

**Comment by andythigpen** [comment]
Unable to reproduce on rails 3.2.3

**Comment by andythigpen** [comment]
Seen in production.  Also effects comments.

**Comment by rpressl** [comment]
Seen in comments for '<=' --but does not seem to occur in the preview function
